[colors.primary]
background = '#1e1e2e'
foreground = '#cdd6f4'

[colors.selection]
text = '#cdd6f4'
background = '#243f75'

[colors.cursor]
text = '#1e1e2e'
cursor = '#89b4fa'

[colors.normal]
black   = '#181825'
red     = '#e84d47'
green   = '#70d66e'
yellow  = '#dbd17b'
blue    = '#5983d1'
magenta = '#7791bb'
cyan    = '#89b4fa'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e05f5f'
green   = '#87e086'
yellow  = '#e8e097'
blue    = '#abd6ff'
magenta = '#4f80a9'
cyan    = '#6879af'
white   = '#ffffff'
